### ISSUE TITLE
GitHub issues label management  

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology.github.io#10]
To have a consistent set of GitHub Labels, it would be convenient to have a repo with all the Labels that we use, without project-specific Labels as `Component:`. 

Once we have such a repo, there are some handy solutions to copy labels from one repo to another: 
* ~~~https://github.com/destan/github-label-manager~~~
* https://github.com/jvandemo/copy-github-labels-cli

**Comment by drdanz** [comment]
I think instead of creating another repo, that we can use this as "base repo"
I suggest copying YARP labels into this repository, remove all YARP-specific labels (like Component, Target, Fixed in) and use them as base for all the other repositories.

**Comment by pattacini** [comment]
Agree with @drdanz.

**Comment by drdanz** [comment]
I tried the first one, but I don't like that I have to insert my password and change my browser security options.
Moreover it doesn't allow me to save changes...

**Comment by traversaro** [comment]
> I tried the first one, but I don't like that I have to insert my password and change my browser security options. 

You can just download the html on your machine and use it from there.

**Comment by drdanz** [comment]
Right... anyway I temporarily changed my password and changed browser options and still didn't work... now I'm testing the node.js one

**Comment by drdanz** [comment]
The [second one](https://github.com/jvandemo/copy-github-labels-cli) worked like a charm in both directions: I copied all labels from YARP to this repo, removed all the useless labels and added one (Status: Help Wanted), and then copied in the opposite direction.

Everything worked as expected, the new label was added to YARP and nothing else was touched.

 The only possible problem is if we want to rename a label, I think that in this case we have to rename it manually on all repos, otherwise the new label will just be created leaving the old one and the issues with the old label won't be updated. I think we can live with that.
